-- Creating Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255),
    password VARCHAR2(255),
    role VARCHAR2(255)
);

-- Creating Sellers Table
CREATE TABLE sellers (
    id NUMBER PRIMARY KEY,
    shopAddress VARCHAR2(255),
    shopName VARCHAR2(255),
    emailSeller VARCHAR2(255),
    phoneNumberSeller VARCHAR2(255),
    CONSTRAINT fk_seller_user FOREIGN KEY (id) REFERENCES users(id)
);

-- Creating Customers Table
CREATE TABLE customers (
    id NUMBER PRIMARY KEY,
    address VARCHAR2(255),
    emailCustomer VARCHAR2(255),
    phoneNumberCustomer NUMBER,
    CONSTRAINT fk_customer_user FOREIGN KEY (id) REFERENCES users(id)
);

-- Creating Categories Table
CREATE TABLE category (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryName VARCHAR2(255)
);

-- Creating Products Table
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    description VARCHAR2(255),
    price NUMBER,
    quantity NUMBER,
    seller_id NUMBER,
    category_id NUMBER,
    CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id)
);

-- Creating Carts Table
CREATE TABLE cart (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    CONSTRAINT fk_cart_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- Creating Cart Items Table
CREATE TABLE cart_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    quantity NUMBER,
    cart_id NUMBER,
    CONSTRAINT fk_cartitem_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_cartitem_cart FOREIGN KEY (cart_id) REFERENCES cart(id)
);

-- Creating Orders Table
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    price NUMBER,
    customer_id NUMBER,
    seller_id NUMBER,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_order_seller FOREIGN KEY (seller_id) REFERENCES sellers(id)
);

-- Creating Order Items Table
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    quantity NUMBER,
    order_id NUMBER,
    CONSTRAINT fk_orderitem_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES orders(id)
);



-- Inserting Sample Users
INSERT INTO users (username, password, role) VALUES
('seller1', '$2a$12$z8nidaerH8bIh4xop2pVDOPK/BIkoqmEOudlZHkcUa3MQu2mtGyOq', 'SELLER');

INSERT INTO users (username, password, role) VALUES
('customer1', '$2a$12$SwhXC3rIXb0xjIXriHbZfO2cgXupUqzpLXtecyPquVOfEUcNfhxVW', 'CUSTOMER');

-- Inserting Sample Sellers
INSERT INTO sellers (id, shopAddress, shopName, emailSeller, phoneNumberSeller) VALUES
(1, '123 Main St', 'Shop One', 'seller1@example.com', '1234567890');

-- Inserting Sample Customers
INSERT INTO customers (id, address, emailCustomer, phoneNumberCustomer) VALUES
(2, '456 Elm St', 'customer1@example.com', 9876543210);

-- Inserting Sample Categories
INSERT INTO category (categoryName) VALUES
('Electronics');

INSERT INTO category (categoryName) VALUES
('Clothing');

-- Inserting Sample Products
INSERT INTO products (name, description, price, quantity, seller_id, category_id) VALUES
('Smartphone', 'Latest model smartphone', 69999, 10, 1, 1);

INSERT INTO products (name, description, price, quantity, seller_id, category_id) VALUES
('T-Shirt', 'Cotton t-shirt', 499, 50, 1, 2);

-- Inserting Sample Carts
INSERT INTO cart (customer_id) VALUES
(2);

-- Inserting Sample Cart Items
INSERT INTO cart_items (product_id, quantity, cart_id) VALUES
(1, 2, 1); -- 2 Smartphones

INSERT INTO cart_items (product_id, quantity, cart_id) VALUES
(2, 3, 1); -- 3 T-Shirts

-- Inserting Sample Orders
INSERT INTO orders (price, customer_id, seller_id) VALUES
(70347, 2, 1); -- Order for the customer with id 2 from seller with id 1

-- Inserting Sample Order Items
INSERT INTO order_items (product_id, quantity, order_id) VALUES
(1, 2, 1); -- 2 Smartphones

INSERT INTO order_items (product_id, quantity, order_id) VALUES
(2, 1, 1); -- 1 T-Shirt
